### ISSUE TITLE
Had bug for search_classufy.ipynb ?

### ISSUE THREAD

**Issue by molyswu** [ksakmann/CarND-Vehicle-Detection#1]
Hi,
    Run search_classufy.ipynb with jupyter notebook ,for bug as folows :
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-765027255be1> in <module>()
----> 1 file0 = images[2]
      2 file1 = images[3]
      3 file2 = images[4]
      4 file3 = images[5]
      5 

IndexError: list index out of range

Thank you !
molyswu

**Comment by molyswu** [comment]
Hi,

IndexError Traceback (most recent call last)
in ()
---->file0 = images[10]
file1 = images[70]
file2 = images[83]
file3 = images[90]

5

IndexError: list index out of range

Thank you !
molyswu

**Comment by ksakmann** [comment]
It's not clear to me where in the code you run into problems, But you have to generate those images first.
